# Generated by Django 3.2.9 on 2021-11-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observer',
            fields=[
                ('observer_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('observer_password', models.CharField(max_length=100)),
                ('observer_email', models.CharField(max_length=100)),
                ('task_id', models.CharField(max_length=100)),
                ('recording_url', models.CharField(max_length=100)),
                ('notes_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('participant_name', models.CharField(max_length=50)),
                ('participant_age', models.CharField(max_length=10)),
                ('participant_gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('recording_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('recording_url', models.CharField(max_length=100)),
                ('notes_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
