# Generated by Django 2.2.12 on 2021-11-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='task_description',
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_descripttion',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_title',
            field=models.CharField(default='Sample Task', max_length=100),
        ),
    ]
