# Generated by Django 2.2.12 on 2021-11-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='participants',
            name='id',
        ),
        migrations.AlterField(
            model_name='participants',
            name='participant_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
