# Generated by Django 3.2.9 on 2021-11-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('user_id', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('task_id', models.IntegerField(max_length=100)),
                ('notes_path', models.CharField(max_length=100)),
                ('notes_descr', models.CharField(max_length=2000)),
            ],
        ),
    ]
