# Generated by Django 2.2.12 on 2021-11-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211124_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='added_on',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='updated_on',
            field=models.TimeField(),
        ),
    ]
