# Generated by Django 2.2.12 on 2021-11-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211128_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='participant_password',
        ),
        migrations.AddField(
            model_name='participants',
            name='participant_age',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participants',
            name='participant_gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participants',
            name='participant_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
